### ISSUE TITLE
Data for the onset notebook

### ISSUE THREAD

**Issue by jundengdeng** [bmcfee/ccrma2018_notebooks#1]
Dear bmcfee,
Thank you very much for sharing the notebooks. When I played around them, some import data are missing, for example, jg_flute-alto-lick.flac and its oneset ground truth. If possible, could you share these data at your convenience. 

Best,
Jun

**Comment by bmcfee** [comment]
The onset dataset is available from https://github.com/CPJKU/onset_db , which has links in the README for the full collection.  It will be better if you download the data from the original sources, since you can then compare over multiple recordings.

**Comment by jundengdeng** [comment]
Thanks for pointing it out. :+1:
